version: 2.1

executors:
  elixir-executor:
    docker:
      - image: elixir:1.9.1
    working_directory: ~/app

  node-executor:
    docker:
      - image: node:10.16.3
    working_directory: ~/app

jobs:
  get_elixir_dependencies:
    executor: elixir-executor
    working_directory: ~/app/back
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - persist_to_workspace:
          root: ./back
          paths: deps

  get_vue_dependencies:
    executor: node-executor
    working_directory: ~/app/front
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: ./front
          paths: node_modules

  test_elixir:
    executor: elixir-executor
    working_directory: ~/app/back
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - attach_workspace:
          at: .
      - run: mix test

  test_vue:
    executor: node-executor
    working_directory: ~/app/front
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - get_elixir_dependencies
      - get_vue_dependencies
      - test_elixir:
          requires:
            - get_elixir_dependencies
      - test_vue:
          requires:
            - get_vue_dependencies